<?php
/******************************************************
 * @package Magento 2 Ui
 * @author https://magefox.com
 * @copyright (C) 2021 - Magefox.Com
 * @license MIT
 *******************************************************/
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */

$script = <<<HTML
{
    ".mui-example": {
        "Magefox_Ui/js/core/app": {
            "components": {
                "example-component": {
                    "component": "Magefox_Ui/js/view/example-component",
                    "title": "Magefox Ui Simple App",
                    "template": "Magefox_Ui/template/view/example-component"
                }
            }
        }
    }
}
HTML;
?>
<pre><?= $script?></pre>
<div class="mui-example">

</div>
<script type="text/x-magento-init">
    <?= $script?>
</script>
